"""Public interface for the edge-consistent RFQ responder demo."""

from rfq_edge.config import (
    FillModelConfig,
    OptimizerConfig,
    SelectionModelConfig,
    ValueModelConfig,
)
from rfq_edge.evaluation import (
    compute_forecast_metrics,
    format_metrics_table,
    liquidity_buckets,
)
from rfq_edge.features import (
    COST_FEATURE_COLUMNS,
    FILL_FEATURE_COLUMNS,
    INVENTORY_FEATURE_COLUMNS,
    SELECTION_FEATURE_COLUMNS,
    VALUE_CATEGORICAL_FEATURES,
    VALUE_FEATURE_COLUMNS,
    VALUE_NUMERIC_FEATURES,
    make_candidate_quote_features,
    make_fill_features,
    make_selection_features,
    make_value_features,
    make_value_target,
    quote_aggressiveness,
)
from rfq_edge.responder_value import (
    FairValue,
    ValueModelParams,
    estimate_fair_value,
    quoted_price,
)
from rfq_edge.responder_fill import FillModelParams, fill_probability
from rfq_edge.responder_selection import SelectionModelParams, adverse_selection_bps
from rfq_edge.responder_optimizer import (
    OptimizerParams,
    QuoteSolution,
    maximize_expected_pnl,
    solve_consistent_edge,
)
from rfq_edge.schema import validate_rfq_schema
from rfq_edge.splits import ChronologicalSplit, chronological_train_test_split
from rfq_edge.costs import CostParams, points_to_cents, rfq_trading_cost_points, trading_cost_bps
from rfq_edge.fill_model import (
    FittedFillModel,
    counterfactual_fill_curve,
    counterfactual_fill_curves_by,
    evaluate_fill_model,
    fill_train_test_split,
    fit_fill_model,
    format_fill_metrics,
    predict_win_probability,
)
from rfq_edge.objective import EdgeComponents, ResponderModels, evaluate_quote
from rfq_edge.optimizer import (
    FittedQuoteModels,
    QuoteDecision,
    aggressiveness_grid,
    demonstrate_quote_optimizer,
    evaluate_quote_grid,
    fit_quote_models,
    format_quote_table,
    optimize_quote,
    quote_from_aggressiveness,
)
from rfq_edge.pipeline import (
    FittedFramework,
    PipelineConfig,
    ResponderDecision,
    cold_start_comparison,
    default_config,
    fit_framework,
    run_book,
    run_responder,
    score_rfq,
)
from rfq_edge.policy_evaluation import (
    PolicyEvaluationResult,
    evaluate_policies,
    run_sensitivity_analysis,
)
from rfq_edge.responders import (
    ALL_RESPONDERS,
    RESPONDER_LABELS,
    ResponderKind,
    ResponderQuote,
    choose_from_grid,
    compare_responders,
    observable_view,
    respond_to_rfq,
    scan_responder_grid,
)
from rfq_edge.simulation_diagnostics import (
    OracleContext,
    append_oracle_objective,
    build_oracle_context,
    oracle_best_decision,
    oracle_conditional_edge,
    oracle_expected_objective,
    oracle_fill_probability,
    oracle_optimal_quote,
    oracle_post_win_value,
    oracle_selection,
    post_win_tilt_by_side,
    realized_selection_summary,
    win_rate_by_aggressiveness_bucket,
)
from rfq_edge.selection_model import (
    FittedSelectionModel,
    V0_OOF_COLUMN,
    counterfactual_selection_curve,
    evaluate_selection_model,
    fit_selection_model,
    format_selection_metrics,
    make_selection_target,
    predict_conditional_mark,
    predict_selection,
    predicted_selection_by_liquidity,
    selection_train_test_split,
)
from rfq_edge.synthetic import (
    BondInfo,
    IssuerInfo,
    RfqRequest,
    Side,
    SyntheticBookSpec,
    SyntheticConfig,
    SyntheticRfq,
    demo_book_spec,
    generate_modeling_book,
    generate_rfq_book,
    make_synthetic_rfqs,
    to_rfq_request,
    validate_synthetic_data,
)
from rfq_edge.value_model import (
    FittedValueModel,
    ValueForecastKind,
    chronological_train_test_split as value_chronological_split,
    evaluate_value_models,
    fit_value_model,
    make_chronological_oof_v0,
    predict_v0,
    predict_value_residual,
)

__all__ = [
    "ALL_RESPONDERS",
    "BondInfo",
    "ChronologicalSplit",
    "CostParams",
    "EdgeComponents",
    "FairValue",
    "FillModelConfig",
    "FillModelParams",
    "FittedFillModel",
    "FittedQuoteModels",
    "FittedSelectionModel",
    "FittedValueModel",
    "FittedFramework",
    "IssuerInfo",
    "OptimizerConfig",
    "OptimizerParams",
    "OracleContext",
    "PipelineConfig",
    "PolicyEvaluationResult",
    "QuoteDecision",
    "QuoteSolution",
    "RESPONDER_LABELS",
    "ResponderDecision",
    "ResponderKind",
    "ResponderModels",
    "ResponderQuote",
    "RfqRequest",
    "SelectionModelConfig",
    "SelectionModelParams",
    "Side",
    "SyntheticBookSpec",
    "SyntheticConfig",
    "SyntheticRfq",
    "COST_FEATURE_COLUMNS",
    "FILL_FEATURE_COLUMNS",
    "INVENTORY_FEATURE_COLUMNS",
    "SELECTION_FEATURE_COLUMNS",
    "V0_OOF_COLUMN",
    "VALUE_CATEGORICAL_FEATURES",
    "VALUE_FEATURE_COLUMNS",
    "VALUE_NUMERIC_FEATURES",
    "ValueForecastKind",
    "ValueModelConfig",
    "ValueModelParams",
    "adverse_selection_bps",
    "aggressiveness_grid",
    "append_oracle_objective",
    "build_oracle_context",
    "choose_from_grid",
    "cold_start_comparison",
    "counterfactual_fill_curve",
    "counterfactual_fill_curves_by",
    "counterfactual_selection_curve",
    "chronological_train_test_split",
    "compare_responders",
    "compute_forecast_metrics",
    "default_config",
    "demonstrate_quote_optimizer",
    "demo_book_spec",
    "estimate_fair_value",
    "evaluate_fill_model",
    "evaluate_policies",
    "evaluate_quote",
    "evaluate_quote_grid",
    "evaluate_selection_model",
    "evaluate_value_models",
    "fill_probability",
    "fill_train_test_split",
    "fit_fill_model",
    "fit_framework",
    "fit_quote_models",
    "fit_selection_model",
    "fit_value_model",
    "format_fill_metrics",
    "format_metrics_table",
    "format_quote_table",
    "format_selection_metrics",
    "generate_modeling_book",
    "generate_rfq_book",
    "liquidity_buckets",
    "make_chronological_oof_v0",
    "make_fill_features",
    "make_candidate_quote_features",
    "make_selection_features",
    "make_selection_target",
    "make_synthetic_rfqs",
    "make_value_features",
    "make_value_target",
    "maximize_expected_pnl",
    "observable_view",
    "optimize_quote",
    "oracle_best_decision",
    "oracle_conditional_edge",
    "oracle_expected_objective",
    "oracle_fill_probability",
    "oracle_optimal_quote",
    "oracle_post_win_value",
    "oracle_selection",
    "points_to_cents",
    "post_win_tilt_by_side",
    "predict_conditional_mark",
    "predict_selection",
    "predict_v0",
    "predict_value_residual",
    "predict_win_probability",
    "predicted_selection_by_liquidity",
    "quote_aggressiveness",
    "quote_from_aggressiveness",
    "quoted_price",
    "realized_selection_summary",
    "respond_to_rfq",
    "rfq_trading_cost_points",
    "run_book",
    "run_responder",
    "run_sensitivity_analysis",
    "scan_responder_grid",
    "score_rfq",
    "selection_train_test_split",
    "solve_consistent_edge",
    "to_rfq_request",
    "trading_cost_bps",
    "validate_rfq_schema",
    "validate_synthetic_data",
    "value_chronological_split",
    "win_rate_by_aggressiveness_bucket",
]

chronological_train_test_split = value_chronological_split
